services:
  db:
    image: postgres:17
    container_name: lqh_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz
      POSTGRES_DB: quizhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: lqh_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
